### ISSUE TITLE
Support 'degit' instead of forking the repo

### ISSUE THREAD

**Issue by Dexterp37** [mozilla-rally/study-template#15]
In #12 it was mentioned that `npx degit mozilla-ion/ion-basic-study my-new-study` could be a good alternative to forking this repo when creating new studies.

This issue is for discussing that improvement and eventually add support for that.

One upside of forking is the ease of providing updates to forked studies: study authors could fetch updates from this repo and rebase accordingly to keep up with the latest updates.

**Comment by pdehaan** [comment]
Ah neat, I didn't realize that degit had an API as well as CLI option.

https://docs.npmjs.com/cli/v6/commands/npm-init has support for initializers as well (which is how create-react-app works, IIUC). Not sure how messy it'd be to try and wrap degit to do some <kbd>npm init @mozilla/ion-basic-study my-new-study</kbd> (or <kbd>npx @mozilla/create-ion-basic-study my-new-study</kbd>).

**Comment by Dexterp37** [comment]
> https://docs.npmjs.com/cli/v6/commands/npm-init has support for initializers as well (which is how create-react-app works, IIUC). Not sure how messy it'd be to try and wrap degit to do some npm init @mozilla/ion-basic-study my-new-study (or npx @mozilla/create-ion-basic-study my-new-study).

I actually like this idea even more!
