### ISSUE TITLE
Dev endpoint capability

### ISSUE THREAD

**Issue by gregobad** [mozilla-rally/study-template#16]
Filing an issue at suggestion of @knowtheory . It would be useful for development purposes to be able to redirect data pings to a local endpoint. This would allow development work to commence prior to signing of a data use agreement and granting of access to the Mozilla environment.

**Comment by Dexterp37** [comment]
Thank you for filing this, @gregobad !

@knowtheory I think we should probably design for this feature in the context of mozilla-ion/ion-core-addon#117 and  mozilla-ion/ion-core-addon#130.

Products using Glean have access to the [Glean Debug View](https://mozilla.github.io/glean/book/user/debugging/debug-ping-view.html) for this specific purpose!
