### ISSUE TITLE
Update study template to bring in playtest improvements

### ISSUE THREAD

**Issue by marniepw** [mozilla-rally/study-template#217]
We've made improvement in the Facebook Pixel Hunt and Search Engine Usage Study extensions that should be brought into the study-template:

- [ ] glean integration from search-engine-usage
- [ ] Chrome support from facebook-pixel-hunt

**Comment by rhelmer** [comment]
The details here are that we've made improvements to the "playtest" mode in https://github.com/mozilla-rally/search-engine-usage-study (it now integrates with Glean.js), and https://github.com/mozilla-rally/facebook-pixel-hunt has some CI improvements and Chrome support (on a branch), which we should pull into the template as well.
