### ISSUE TITLE
add an integration test runner for the study template

### ISSUE THREAD

**Issue by hamilton** [mozilla-rally/study-template#26]

**Comment by knowtheory** [comment]
I am going to schedule a meeting to discuss how we want to engage with partners around this, and how much roadway we want to pave for them w/r/t testing.

If you're interested in participating, please let me know!

**Comment by Dexterp37** [comment]
Yes please, @knowtheory , include me in the meeting.

Note that we should probably have a test-runner regardless: whether or not we'll expect partners to use it, it's a different story IMHO  :)
