### ISSUE TITLE
Linting for Rollup output

### ISSUE THREAD

**Issue by jonathanmayer** [mozilla-rally/study-template#67]
A key component of the `study-template` concept is using Node and Rollup to resolve dependencies, rather than copying and pasting external libraries. While this approach has significant advantages for study review and maintenance (and is clearly the right way to go), one drawback is that it can introduce ESLint warnings for external libraries (e.g., Readability). Another (hypothetical) drawback is that we could unintentionally percolate ESLint instructions from input files to Rollup output, with unpredictable effects.

With the old approach, we could prepend ESLint instructions to an external library, ignore the library in the ESLint configuration file, or just live with ESLint warnings for a file we knew was a dependency. With the new approach, we have less flexibility: Rollup intermingles our code with dependency code, `web-ext lint` necessarily runs ESLint on Rollup output (`background.js`), and `web-ext lint` ignores our ESLint configuration file (by design). The outcome we want is linting for our code, but no linting (or clearly delineated linting) for dependency code.

One possible fix would be to strip out comments (or just ESLint comments) when generating Rollup output and prepend an ESLint ignore instruction that applies to the entire file. Another option would be to wrap only Node dependencies in ESLint ignore instructions. I don't have much preference, so long as these warnings from dependencies aren't interpreted as blockers for studies.

**Comment by Dexterp37** [comment]
> 
> 
> A key component of the `study-template` concept is using Node and Rollup to resolve dependencies, rather than copying and pasting external libraries. While this approach has significant advantages for study review and maintenance (and is clearly the right way to go), one drawback is that it can introduce ESLint warnings for external libraries (e.g., Readability). Another (hypothetical) drawback is that we could unintentionally percolate ESLint instructions from input files to Rollup output, with unpredictable effects.

Note that external libraries properly imported and managed through NPM are not linted. The fix for external library is to not vendor them, but rather use the package management system.

> With the old approach, we could prepend ESLint instructions to an external library, ignore the library in the ESLint configuration file, or just live with ESLint warnings for a file we knew was a dependency. With the new approach, we have less flexibility: Rollup intermingles our code with dependency code, `web-ext lint` necessarily runs ESLint on Rollup output (`background.js`), and `web-ext lint` ignores our ESLint configuration file (by design). The outcome we want is linting for our code, but no linting (or clearly delineated linting) for dependency code.

The study template linter lints the original files, not the assembled files. web-ext lints the add-on in its entirety (and so it lints the assembled background/content scripts). Unfortunately web-ext does not support tweaking the linting rules (see mozilla/addons-linter#2941 for example), but that's a bug in web-ext that should be fixed there.

> One possible fix would be to strip out comments (or just ESLint comments) when generating Rollup output and prepend an ESLint ignore instruction that applies to the entire file. Another option would be to wrap only Node dependencies in ESLint ignore instructions. I don't have much preference, so long as these warnings from dependencies aren't interpreted as blockers for studies.

I think the immediate fix here is to stop vendoring Readability.js and add it as a dependency. For the web-ext problem, we should probably file an issue there and discuss its prioritization.

**Comment by jonathanmayer** [comment]
If you're comfortable with relying on `eslint` rather than `web-ext lint` for now,  that's fine by me. The goal of this issue was to accommodate your strong preference for eliminating `web-ext lint` warnings before shipping the add-on.

**Comment by Dexterp37** [comment]
I think we can live with the current status quo for now :-) We should get this fixed in web-ext but, in the short term, is fine to ignore the know warnings that we see as of today.
